---
- name: Install packages
  include_tasks: ../../install_packages_template.yml
  tags: desktop

- include: archlinux.yml
  when: ansible_distribution == 'Archlinux'
  tags: desktop

- include: xfce.yml
  tags: desktop

# - include: gnome.yml
#   when: "'GNOME' in desktop_info.stdout"
#   tags: desktop

- include: ranger.yml
  tags: desktop

- include: tmux.yml
  tags: desktop

- include: zsh.yml
  tags: desktop
