---
- name: Create Ranger devicons plugins folder
  file:
    path: '{{ home_dir }}/.config/ranger/plugins'
    state: directory
    recurse: yes
    mode: '777'
  changed_when: false

- name: Install Ranger devicons plugin
  git:
    repo: 'https://github.com/alexanderjeurissen/ranger_devicons'
    dest: '{{ home_dir }}/.config/ranger/plugins/ranger_devicons'
    depth: '1'
    force: yes
  changed_when: false

- name: Install Ueberzug for Image preview in Ranger
  pip:
    name: ueberzug
  changed_when: false # this is because in test scenarios (in a docker container) do not cover graphical stuff
  ignore_errors: yes # this is because in test scenarios (in a docker container) do not cover graphical stuff
