---
- name: Install Oh My Zsh
  script: ../scripts/install-oh-my-zsh.sh {{ username }}
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255

- name: Install Powerlevel10k Theme
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '{{ home_dir }}/powerlevel10k'
    depth: '1'

- name: Install Oh My Zsh Plugins
  git:
    repo: '{{ item }}'
    dest: '{{ home_dir }}/.oh-my-zsh/custom/plugins/{{ item.split("/") | last }}'
  with_items: '{{ ohmyzsh_plugins }}'
  ignore_errors: yes

- name: Set Oh My Zsh Plugins Permissions
  file:
    path: '{{ home_dir }}/.oh-my-zsh/custom/plugins'
    state: directory
    recurse: yes
    mode: '700'
  changed_when: false

- name: Set Zsh as default shell
  user:
    name: '{{ username }}'
    shell: /usr/bin/zsh
  become: true
